import type { AiTip } from '../db/types'

/** 内置 AI / 学习方法小贴士库（首启动写入本地库） */
export const TIP_SEED: Omit<AiTip, 'id'>[] = [
  {
    title: '用 AI 做「错题教练」，别只问答案',
    body: '把做错的四级阅读题原文 + 你的选项发给 AI，提示词：「不要直接给答案，先问我三个引导性问题帮我定位错因，再讲解题思路」。搞懂错因比多做十道题有效。',
    category: '英语',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '影子跟读法（Shadowing）练口语',
    body: '选一段 1 分钟美剧/播客音频，落后原声 1-2 秒同步复述，连续 15 分钟。重点是模仿语调和停顿，不是背单词。坚持一个月，口语流利度会明显变化。',
    category: '英语',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '外刊阅读：三遍法',
    body: '第一遍通读不查词，猜大意；第二遍查高频生词并记入生词本；第三遍摘一个好句仿写。花 25 分钟比泛读一小时收获大。',
    category: '阅读',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '30 分钟运动的「最低承诺」原则',
    body: '状态差的时候允许自己只做 5 分钟，但必须换上运动服开始。绝大多数情况下你会做完剩下的 25 分钟。关键是把「开始」的阻力降到最低。',
    category: '运动',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '普拉提比跑步更适合改善体态',
    body: '长期久坐的女生常有圆肩 + 骨盆前倾。每周 3 次 30 分钟普拉提，配合日常提醒自己收核心，两个月体态变化会比单纯有氧明显。',
    category: '运动',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '记录饮食，而不是节食',
    body: '先连续记录两周，不做任何限制。你会自然发现「隐形热量」在哪里（奶茶、坚果、酱料）。从削减这些开始比盲目少吃更容易坚持。',
    category: '饮食',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '蛋白质先吃',
    body: '每餐先吃蛋白质和蔬菜，最后吃主食，餐后血糖更平稳，下午不容易犯困，也更不容易加餐。',
    category: '饮食',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '番茄钟 + 任务拆解',
    body: '任何任务如果 25 分钟做不完，说明它其实是一堆任务。先花 3 分钟把它拆成 3-5 个可完成的小步骤，再开始计时。',
    category: '效率',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '让 AI 扮演面试官',
    body: '把目标岗位的 JD 贴给 AI，让它扮演外企 HR 用英文提问，你用英文回答，再请它按「结构 / 词汇 / 语法」三点评分并给出改写版本。这是最便宜的口语陪练。',
    category: '英语',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '每周复盘的三句话模板',
    body: '①这周最有成就感的一件事；②一件没做到、且原因具体的事；③下周只改这一件事。复盘最怕写成流水账，三句话逼你做取舍。',
    category: '复盘',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '民办本科 + 香港读研的路径要点',
    body: '港校授课型硕士看重：本科 GPA、雅思/托福、实习与推荐信、PS 的动机叙事。大一就该开始拉高 GPA，这是最难补的一项。',
    category: '升学',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '焦虑时先写下来，再决定',
    body: '把担心的事逐条写下来，标注「能控制 / 不能控制」。只对「能控制」的那一列做下一步动作，其余的划掉。写下来这个动作本身就能降低焦虑。',
    category: '情绪',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '睡前 10 分钟复盘代替刷手机',
    body: '记录今天的心情 + 一件小确幸。连续记录一个月后回看，你会发现情绪波动其实有规律，也能看到自己真正在意什么。',
    category: '情绪',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: 'Excel 学习的正确顺序',
    body: '先搞定三件事：绝对引用 $、数据透视表、XLOOKUP/VLOOKUP。这三个能解决 80% 的实际工作，比背函数大全有用得多。',
    category: '技能',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '英语词汇：用「词组」代替「单词」',
    body: '孤立背单词忘得快。把新词放进一个你自己造的句子里，最好跟你的生活相关（今天吃了什么、心情如何），记忆留存率会高很多。',
    category: '英语',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
  {
    title: '新闻评论训练批判性思维',
    body: '读完一条新闻，强制自己写三行：事实是什么 / 作者的立场是什么 / 我同意和存疑的各是什么。每周三条，三个月后思考质量会完全不同。',
    category: '思辨',
    saved: 0,
    applied: 0,
    createdAt: 0,
  },
]
